"""empty message

Revision ID: 8b6dd63386b6
Revises: f26c9ee05f04
Create Date: 2020-06-07 16:39:43.601563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b6dd63386b6'
down_revision = 'f26c9ee05f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('avatar_path', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'avatar_path')
    # ### end Alembic commands ###
