"""empty message

Revision ID: f26c9ee05f04
Revises: c63982fce5a1
Create Date: 2020-06-07 15:47:04.009600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26c9ee05f04'
down_revision = 'c63982fce5a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('games_lost', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('games_played', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('shots_done', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'shots_done')
    op.drop_column('user', 'games_played')
    op.drop_column('user', 'games_lost')
    # ### end Alembic commands ###
